"""
Edge-TTS voice engine for J.A.R.V.I.S.

The engine streams MP3 frames from Microsoft Edge-TTS directly into ffplay
when available. It can also synthesize bytes for HTTP clients such as the
existing frontend /tts endpoint.
"""
from __future__ import annotations

import asyncio
import shutil
import time
from collections import OrderedDict
from dataclasses import dataclass
from typing import AsyncIterator, Protocol

try:
    import edge_tts
except ImportError:  # pragma: no cover - exercised only when dependency missing
    edge_tts = None

try:
    import psutil
except ImportError:  # pragma: no cover
    psutil = None


DEFAULT_JARVIS_VOICE = "en-GB-RyanNeural"

JARVIS_VOICE_SUGGESTIONS = [
    {
        "name": "en-GB-RyanNeural",
        "style": "UK male, calm, deep enough for a J.A.R.V.I.S profile",
    },
    {
        "name": "en-US-GuyNeural",
        "style": "US male, confident, clean assistant tone",
    },
    {
        "name": "en-US-ChristopherNeural",
        "style": "US male, mature and slightly deeper",
    },
    {
        "name": "en-US-EricNeural",
        "style": "US male, crisp and responsive",
    },
    {
        "name": "en-GB-ThomasNeural",
        "style": "UK male, formal and measured",
    },
]


class VoiceEngineError(RuntimeError):
    """Raised when a voice adapter cannot synthesize or play speech."""


class VoiceAdapter(Protocol):
    """Adapter boundary for Edge, Piper, Coqui, pyttsx3, or future engines."""

    async def speak(self, text: str) -> None:
        """Synthesize and play text."""

    async def synthesize_to_bytes(self, text: str) -> bytes:
        """Return audio bytes suitable for HTTP delivery."""

    async def stop(self) -> None:
        """Interrupt active playback."""

    async def pause(self) -> None:
        """Pause active playback where supported."""

    async def resume(self) -> None:
        """Resume active playback where supported."""


@dataclass(frozen=True)
class VoiceConfig:
    voice_name: str = DEFAULT_JARVIS_VOICE
    rate: str = "+0%"
    pitch: str = "-2Hz"
    volume: str = "+0%"


class JarvisVoice:
    """
    Low-latency Edge-TTS voice adapter.

    Edge-TTS itself is network-backed, but synthesis begins yielding MP3 bytes
    before the full utterance completes. Piping those bytes into ffplay avoids
    the slow "write whole mp3, then play" path.
    """

    def __init__(
        self,
        voice_name: str = DEFAULT_JARVIS_VOICE,
        rate: str = "+0%",
        pitch: str = "-2Hz",
        volume: str = "+0%",
        cache_size: int = 32,
        prefer_ffplay: bool = True,
    ) -> None:
        self.config = VoiceConfig(
            voice_name=voice_name,
            rate=self._normalize_percent(rate),
            pitch=self._normalize_pitch(pitch),
            volume=self._normalize_percent(volume),
        )
        self.cache_size = cache_size
        self.prefer_ffplay = prefer_ffplay
        self._cache: OrderedDict[str, bytes] = OrderedDict()
        self._current_process: asyncio.subprocess.Process | None = None
        self._playback_lock = asyncio.Lock()
        self._ffplay_path = shutil.which("ffplay")

    async def speak(self, text: str) -> None:
        """
        Convert text to speech and play it immediately.

        If ffplay exists, audio is streamed into ffplay as Edge-TTS yields MP3
        frames. If ffplay is unavailable, playback falls back to pygame after
        full synthesis.
        """
        clean_text = self._clean_text(text)
        if not clean_text:
            return

        async with self._playback_lock:
            cached = self._get_cached(clean_text)
            if cached:
                await self._play_bytes(cached)
                return

            if self.prefer_ffplay and self._ffplay_path:
                await self._stream_to_ffplay(clean_text)
                return

            audio = await self.synthesize_to_bytes(clean_text)
            await self._play_bytes(audio)

    async def synthesize_to_bytes(self, text: str) -> bytes:
        """Return MP3 bytes generated by Edge-TTS."""
        clean_text = self._clean_text(text)
        if not clean_text:
            return b""

        cached = self._get_cached(clean_text)
        if cached:
            return cached

        audio = bytearray()
        async for chunk in self._edge_audio_stream(clean_text):
            audio.extend(chunk)

        audio_bytes = bytes(audio)
        self._remember(clean_text, audio_bytes)
        return audio_bytes

    async def set_voice(self, voice_name: str) -> None:
        """Switch the active Edge voice."""
        self.config = VoiceConfig(
            voice_name=voice_name.strip(),
            rate=self.config.rate,
            pitch=self.config.pitch,
            volume=self.config.volume,
        )
        self._cache.clear()

    async def set_rate(self, rate: str | int) -> None:
        """Set speech speed, for example '+8%', '-10%', or 8."""
        self.config = VoiceConfig(
            voice_name=self.config.voice_name,
            rate=self._normalize_percent(rate),
            pitch=self.config.pitch,
            volume=self.config.volume,
        )
        self._cache.clear()

    async def set_pitch(self, pitch: str | int) -> None:
        """Set pitch, for example '-2Hz', '+4Hz', or -2."""
        self.config = VoiceConfig(
            voice_name=self.config.voice_name,
            rate=self.config.rate,
            pitch=self._normalize_pitch(pitch),
            volume=self.config.volume,
        )
        self._cache.clear()

    async def warm_start(self) -> None:
        """
        Prime Edge-TTS and local playback dependencies.

        This does not play audio. It synthesizes a tiny phrase into memory so
        DNS/TLS/service startup costs are paid before the first real response.
        """
        try:
            await self.synthesize_to_bytes("Online.")
        except Exception:
            # Warmup should never prevent the assistant from starting.
            return

    async def benchmark_latency(self, text: str = "Systems online, sir.") -> dict[str, float | str]:
        """
        Measure Edge-TTS time to first audio chunk and full synthesis time.
        """
        clean_text = self._clean_text(text)
        started = time.perf_counter()
        first_audio_at: float | None = None
        total_bytes = 0

        async for chunk in self._edge_audio_stream(clean_text):
            total_bytes += len(chunk)
            if first_audio_at is None:
                first_audio_at = time.perf_counter()

        finished = time.perf_counter()
        return {
            "voice": self.config.voice_name,
            "time_to_first_audio_ms": round(((first_audio_at or finished) - started) * 1000, 2),
            "full_synthesis_ms": round((finished - started) * 1000, 2),
            "bytes": float(total_bytes),
        }

    async def stop(self) -> None:
        """Interrupt active playback."""
        process = self._current_process
        if process and process.returncode is None:
            process.kill()
            try:
                await process.wait()
            except Exception:
                pass
        self._current_process = None
        await self._pygame_music_command("stop")

    async def pause(self) -> None:
        """Pause active playback when psutil can suspend the player process."""
        if psutil is None or not self._current_process:
            await self._pygame_music_command("pause")
            return
        if self._current_process.returncode is None:
            psutil.Process(self._current_process.pid).suspend()

    async def resume(self) -> None:
        """Resume active playback when psutil can resume the player process."""
        if psutil is None or not self._current_process:
            await self._pygame_music_command("unpause")
            return
        if self._current_process.returncode is None:
            psutil.Process(self._current_process.pid).resume()

    async def _edge_audio_stream(self, text: str) -> AsyncIterator[bytes]:
        if edge_tts is None:
            raise VoiceEngineError(
                "edge-tts is not installed. Run: pip install edge-tts"
            )

        communicate = edge_tts.Communicate(
            text=text,
            voice=self.config.voice_name,
            rate=self.config.rate,
            pitch=self.config.pitch,
            volume=self.config.volume,
        )
        async for chunk in communicate.stream():
            if chunk["type"] == "audio":
                yield chunk["data"]

    async def _stream_to_ffplay(self, text: str) -> None:
        if not self._ffplay_path:
            raise VoiceEngineError("ffplay was not found on PATH.")

        process = await asyncio.create_subprocess_exec(
            self._ffplay_path,
            "-nodisp",
            "-autoexit",
            "-loglevel",
            "quiet",
            "-fflags",
            "nobuffer",
            "-flags",
            "low_delay",
            "-probesize",
            "32",
            "-analyzeduration",
            "0",
            "-i",
            "pipe:0",
            stdin=asyncio.subprocess.PIPE,
            stdout=asyncio.subprocess.DEVNULL,
            stderr=asyncio.subprocess.DEVNULL,
        )
        self._current_process = process

        try:
            async for audio_chunk in self._edge_audio_stream(text):
                if process.stdin is None or process.returncode is not None:
                    break
                process.stdin.write(audio_chunk)
                await process.stdin.drain()

            if process.stdin:
                process.stdin.close()
            await process.wait()
        except (BrokenPipeError, ConnectionResetError):
            pass
        finally:
            self._current_process = None

    async def _play_bytes(self, audio_bytes: bytes) -> None:
        if not audio_bytes:
            return
        if self._ffplay_path:
            process = await asyncio.create_subprocess_exec(
                self._ffplay_path,
                "-nodisp",
                "-autoexit",
                "-loglevel",
                "quiet",
                "-i",
                "pipe:0",
                stdin=asyncio.subprocess.PIPE,
                stdout=asyncio.subprocess.DEVNULL,
                stderr=asyncio.subprocess.DEVNULL,
            )
            self._current_process = process
            try:
                if process.stdin:
                    process.stdin.write(audio_bytes)
                    await process.stdin.drain()
                    process.stdin.close()
                await process.wait()
            finally:
                self._current_process = None
            return

        await self._play_bytes_with_pygame(audio_bytes)

    async def _play_bytes_with_pygame(self, audio_bytes: bytes) -> None:
        """
        Emergency playback path when ffplay is unavailable.

        This buffers the full MP3, so it is not the preferred low-latency mode.
        """
        import io

        try:
            import pygame
        except ImportError as exc:  # pragma: no cover
            raise VoiceEngineError(
                "No playback backend available. Install ffmpeg/ffplay or pygame."
            ) from exc

        def play_blocking() -> None:
            pygame.mixer.init()
            pygame.mixer.music.load(io.BytesIO(audio_bytes), "mp3")
            pygame.mixer.music.play()
            while pygame.mixer.music.get_busy():
                time.sleep(0.02)

        await asyncio.to_thread(play_blocking)

    async def _pygame_music_command(self, command: str) -> None:
        """Best-effort control for the pygame fallback playback backend."""
        try:
            import pygame

            if not pygame.mixer.get_init():
                return

            action = getattr(pygame.mixer.music, command)
            await asyncio.to_thread(action)
        except Exception:
            return

    def _get_cached(self, text: str) -> bytes | None:
        key = self._cache_key(text)
        value = self._cache.get(key)
        if value:
            self._cache.move_to_end(key)
        return value

    def _remember(self, text: str, audio: bytes) -> None:
        if self.cache_size <= 0:
            return
        key = self._cache_key(text)
        self._cache[key] = audio
        self._cache.move_to_end(key)
        while len(self._cache) > self.cache_size:
            self._cache.popitem(last=False)

    def _cache_key(self, text: str) -> str:
        return "|".join(
            [
                self.config.voice_name,
                self.config.rate,
                self.config.pitch,
                self.config.volume,
                text,
            ]
        )

    @staticmethod
    def _clean_text(text: str) -> str:
        return " ".join((text or "").strip().split())

    @staticmethod
    def _normalize_percent(value: str | int) -> str:
        if isinstance(value, int):
            return f"{value:+d}%"
        value = value.strip()
        if value.endswith("%"):
            return value if value.startswith(("+", "-")) else f"+{value}"
        number = int(value)
        return f"{number:+d}%"

    @staticmethod
    def _normalize_pitch(value: str | int) -> str:
        if isinstance(value, int):
            return f"{value:+d}Hz"
        value = value.strip()
        if value.endswith("Hz"):
            return value if value.startswith(("+", "-")) else f"+{value}"
        number = int(value)
        return f"{number:+d}Hz"
